name = "DynamicSparseArrays"
uuid = "8086fd22-9a0c-46a5-a6c8-6e24676501fe"
authors = ["Guillaume Marques <guillaume.marques@protonmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
